module.exports = function(RED) {
    var ui = undefined;

    function ChineseChessNode(config) {
        try {
            var node = this;
            if (ui === undefined) {
                ui = RED.require("node-red-dashboard")(RED);
            }
            RED.nodes.createNode(this, config);

            var chessWidth = config.chessWidth || 400;
            var chessHeight = config.chessHeight || 400;
            var orientation = config.orientation || 'red';
            var showControls = config.showControls !== undefined ? config.showControls : true;

            // HTML 模板 - 使用唯一 ID 避免冲突
            var format = 
            '<div style="text-align: center; padding: 10px;">' +
                '<div data-ng-attr-id="{{containerId}}"></div>' +
                '<div data-ng-attr-id="{{infoId}}" style="margin-top: 10px; padding: 8px; background: #f5f5f5; border-radius: 4px; min-height: 20px;"></div>' +
            '</div>';

            var initControllerCode = [
                '$scope.containerId = "chess-container-" + $scope.$id;',
                '$scope.infoId = "info-panel-" + $scope.$id;',
                '',
                'function init() {',
                '    var containerId = $scope.containerId;',
                '    var infoId = $scope.infoId;',
                '    var container = document.getElementById(containerId);',
                '    var infoPanel = document.getElementById(infoId);',
                '    var game = null;',
                '    var renderer = null;',
                '',
                '    // 加载核心脚本',
                '    if (!window["ChineseChess"]) {',
                '        var script = document.createElement("script");',
                '        script.src = "/resources/node-red-contrib-chinese-chess/chinese-chess-core.js";',
                '        script.onload = function() {',
                '            doInit();',
                '        };',
                '        document.head.appendChild(script);',
                '    } else {',
                '        doInit();',
                '    }',
                '',
                '    function doInit() {',
                '        // 初始化游戏',
                '        game = window["ChineseChess"].createGame({',
                '            onEvent: function(event, data) {',
                '                if (event === "move" || event === "back" || event === "reset" || event === "goto") {',
                '                    // 输出当前状态给 Node-RED',
                '                    $scope.send({',
                '                        payload: {',
                '                            fen: game.getFEN(),',
                '                            pgn: game.getPGN({includeHeader: false}),',
                '                            pgnArray: game.getPGN({format: "array"}),',
                '                            pgnFull: game.getPGN(),',
                '                            currentStep: game.history.length,',
                '                            totalSteps: game.history.length,',
                '                            turn: game.currentMoveIndex % 2 === 0 ? "red" : "black",',
                '                            history: game.history,',
                '                        }',
                '                    });',
                '                    updateInfo();',
                '                }',
                '            }',
                '        });',
                '',
                '        renderer = window["ChineseChess"].createRenderer(game, container, {',
                '            size: ' + chessWidth + ',',
                '            showControls: ' + showControls + ',',
                '            onUserMove: function(fromX, fromY, toX, toY, moveStr) {',
                '                var success = game.move(fromX, fromY, toX, toY);',
                '                if (success && game.script) {',
                '                    var branch = game.matchBranch(moveStr);',
                '                    if (branch) {',
                '                        showBranches();',
                '                        if (branch.next) {',
                '                            game.currentNode = getNodeById(game.script, branch.next);',
                '                        }',
                '                        updateInfo(branch.note);',
                '                    } else {',
                '                        updateInfo("未匹配剧本走法: " + moveStr);',
                '                    }',
                '                }',
                '                if (success && renderer) {',
                '                    renderer.render();',
                '                }',
                '            }',
                '        });',
                '',
                '        function getNodeById(script, id) {',
                '            if (!script || !script.nodes) return null;',
                '            return script.nodes.find(function(n) { return n.id === id; });',
                '        }',
                '',
                '        function updateInfo(text) {',
                '            if (text && infoPanel) {',
                '                infoPanel.innerHTML = "<strong>提示:</strong> " + text;',
                '            } else if (infoPanel && game) {',
                '                infoPanel.innerHTML = "<strong>Move:</strong> " + game.history.length +',
                '                    ", <strong>Turn:</strong> " + (game.currentMoveIndex % 2 === 0 ? "Red" : "Black");',
                '            }',
                '        }',
                '',
                '        function showBranches() {',
                '            if (!game.currentNode || !game.currentNode.branches || !infoPanel) return;',
                '            var html = "<div><strong>可选分支:</strong></div>";',
                '            game.currentNode.branches.forEach(function(b) {',
                '                var cls = "branch branch-" + (b.type || "main");',
                '                var style = "display: inline-block; margin: 2px; padding: 4px 8px; border-radius: 4px; cursor: pointer; ";',
                '                if (b.type === "main") style += "background: #a6e22e;";',
                '                else if (b.type === "soft") style += "background: #fd971f;";',
                '                else if (b.type === "trap") style += "background: #f92672;";',
                '                else style += "background: #ae81ff;";',
                '                html += "<span class=\'" + cls + "\' style=\'" + style + "\' data-move=\'" + b.move + "\'>" + (b.label || b.type) + ": " + (b.note || "") + "</span>";',
                '            });',
                '            infoPanel.innerHTML = html;',
                '            // 绑定点击事件',
                '            infoPanel.querySelectorAll(".branch").forEach(function(el) {',
                '                el.addEventListener("click", function() {',
                '                    var moveStr = el.getAttribute("data-move");',
                '                    if (window["ChineseChess"]) {',
                '                        var m = window["ChineseChess"].parseMoveStr(moveStr);',
                '                        if (m && game) {',
                '                            game.move(m.fromX, m.fromY, m.toX, m.toY);',
                '                            if (renderer) renderer.render();',
                '                        }',
                '                    }',
                '                });',
                '            });',
                '        }',
                '',
                '        game.reset();',
                '        if (renderer) {',
                '            renderer.render();',
                '        }',
                '        updateInfo();',
                '',
                '        // 监听来自后端的消息',
                '        $scope.$watch("msg", function(msg) {',
                '            if (!msg) return;',
                '            console.log("[chinese-chess] $watch msg received:", JSON.stringify(msg.payload));',
                '            if (msg.payload && msg.payload.action) {',
                '                var data = msg.payload;',
                '                switch (data.action) {',
                '                    case "load":',
                '                        if (data.pgn) {',
                '                            var result = game.loadPGN(data.pgn);',
                '                            if (result.success) {',
                '                                updateInfo("PGN loaded: " + result.loaded + "/" + result.total + " moves valid");',
                '                                if (renderer) renderer.render();',
                '                            } else {',
                '                                var errorMsg = "PGN validation failed: " + result.errors.length + " errors";',
                '                                if (result.errors.length > 0) {',
                '                                    errorMsg += "<br>&bull; " + result.errors.slice(0, 3).join("<br>&bull; ");',
                '                                    if (result.errors.length > 3) errorMsg += "<br>&bull; ...and " + (result.errors.length - 3) + " more errors";',
                '                                }',
                '                                updateInfo(errorMsg);',
                '                            }',
                '                        } else if (data.script) {',
                '                            game.script = data.script;',
                '                            game.reset();',
                '                            updateInfo("Script loaded");',
                '                        } else if (data.fen) {',
                '                            var fenResult = game.loadFEN(data.fen);',
                '                            if (fenResult) { updateInfo("FEN loaded"); } else { updateInfo("FEN load failed, invalid format"); }',
                '                        }',
                '                        break;',
                '                    case "loadfen":',
                '                        if (data.fen) {',
                '                            var fenResult = game.loadFEN(data.fen);',
                '                            if (fenResult) { updateInfo("FEN loaded"); } else { updateInfo("FEN load failed, invalid format"); }',
                '                        }',
                '                        break;',
                '                    case "next":',
                '                        game.next();',
                '                        break;',
                '                    case "prev":',
                '                        game.back();',
                '                        break;',
                '                    case "goto":',
                '                        if (typeof data.step === "number") {',
                '                            game.goto(data.step);',
                '                        }',
                '                        break;',
                '                    case "move":',
                '                        if (data.from && data.to) {',
                '                            game.move(',
                '                                parseInt(data.from[0], 10),',
                '                                parseInt(data.from[1], 10),',
                '                                parseInt(data.to[0], 10),',
                '                                parseInt(data.to[1], 10));',
                '                        }',
                '                        break;',
                '                    default:',
                '                        console.log("[chinese-chess] received action:", data.action);',
                '                        // 优先处理中文记谱：如 "炮二平五" "马8进7" "兵三进一" 等',
                '                        var moveText = data.action ? data.action.trim() : "";',
                '                        console.log("[chinese-chess] moveText:", moveText, "length:", moveText.length);',
                '                        if (moveText.length >= 4 && game) {',
                '                            var pieceChars = ["帅", "仕", "相", "马", "车", "炮", "兵", "将", "士", "象", "卒"];',
                '                            var positionPrefixes = ["前", "后"];',
                '                            var firstChar = moveText[0];',
                '                            var secondChar = moveText[1];',
                '                            console.log("[chinese-chess] first char:", firstChar, "second char:", secondChar);',
                '                            var isValidFormat = (pieceChars.indexOf(firstChar) >= 0) || (positionPrefixes.indexOf(firstChar) >= 0 && pieceChars.indexOf(secondChar) >= 0);',
                '                            if (isValidFormat) {',
                '                                var coord = window["ChineseChess"].chineseMoveToCoordinate(moveText, game);',
                '                                console.log("[chinese-chess] parsed coord:", coord);',
                '                                if (coord) {',
                '                                    // 先检查起点是否真的有对应棋子',
                '                                    var piece = game.board.get(coord.fromX, coord.fromY);',
                '                                    if (!piece) {',
                '                                        updateInfo("⚠️ 非法走法: " + moveText + " (起点无对应棋子)");',
                '                                        $scope.send({',
                '                                            payload: {',
                '                                                error: "非法走法",',
                '                                                message: moveText + " (起点无对应棋子)",',
                '                                                success: false',
                '                                            }',
                '                                        });',
                '                                    } else {',
                '                                        var success = game.move(coord.fromX, coord.fromY, coord.toX, coord.toY);',
                '                                        console.log("[chinese-chess] move success:", success);',
                '                                        if (success) {',
                '                                            updateInfo("✅ 执行走法: " + moveText);',
                '                                            // 成功走法输出在 game.move 里的事件已经触发了标准输出',
                '                                        } else {',
                '                                            updateInfo("⚠️ 非法走法: " + moveText + " (不符合规则)");',
                '                                            $scope.send({',
                '                                                payload: {',
                '                                                    error: "非法走法",',
                '                                                    message: moveText + " (不符合规则)",',
                '                                                    success: false',
                '                                                }',
                '                                            });',
                '                                        }',
                '                                    }',
                '                                } else {',
                '                                    updateInfo("❌ 无法解析走法: " + moveText);',
                '                                    $scope.send({',
                '                                        payload: {',
                '                                            error: "无法解析走法",',
                '                                            message: moveText,',
                '                                            success: false',
                '                                        }',
                '                                    });',
                '                                }',
                '                            }',
                '                        }',
                '                        // 如果payload包含fen，尝试加载',
                '                        if (typeof data.fen === "string" && data.fen.indexOf("/") >= 0) {',
                '                            var fenResult = game.loadFEN(data.fen);',
                '                            if (fenResult) { updateInfo("FEN loaded"); } else { updateInfo("FEN load failed, invalid format"); }',
                '                        }',
                '                        break;',
                '                    case "getPGN":',
                '                        $scope.send({',
                '                            payload: {',
                '                                action: "getPGN",',
                '                                pgn: game.getPGN(),',
                '                                pgnText: game.getPGN({includeHeader: false}),',
                '                                pgnArray: game.getPGN({format: "array"}),',
                '                                history: game.history',
                '                            }',
                '                        });',
                '                        break;',
                '                    case "getFEN":',
                '                    case "getStatus":',
                '                        $scope.send({',
                '                            payload: {',
                '                                action: "getStatus",',
                '                                fen: game.getFEN(),',
                '                                pgn: game.getPGN(),',
                '                                pgnArray: game.getPGN({format: "array"}),',
                '                                currentStep: game.history.length,',
                '                                totalSteps: game.history.length,',
                '                                turn: game.currentMoveIndex % 2 === 0 ? "red" : "black",',
                '                                history: game.history',
                '                            }',
                '                        });',
                '                        break;',
                '                    case "reset":',
                '                        game.reset();',
                '                        break;',
                '                }',
                '                if (renderer) {',
                '                    renderer.render();',
                '                }',
                '            } else if (typeof msg.payload === "string" && msg.payload.indexOf("/") >= 0) {',
                '                // 直接传入 FEN 字符串，尝试加载',
                '                var fenResult = game.loadFEN(msg.payload);',
                '                if (renderer) {',
                '                    renderer.render();',
                '                }',
                '                if (fenResult) { updateInfo("FEN loaded"); } else { updateInfo("FEN load failed, invalid format"); }',
                '            }',
                '        });',
                '    }',
                '}',
                '',
                '    // 使用 AngularJS 生命周期保证 DOM 已经插入',
                '    $scope.$evalAsync(function() {',
                '        setTimeout(init, 50);',
                '    });'
            ].join('\n');

            var initController = new Function('$scope', 'events', initControllerCode);

            var done = ui.addWidget({
                node: node,
                format: format,
                templateScope: "local",
                group: config.group,
                order: config.order,
                width: config.width,
                height: config.height,
                emitOnlyNewValues: false,
                forwardInputMessages: true,
                storeFrontEndInputAsState: false,
                beforeSend: function (msg, orig) {
                    if (orig) {
                        return orig.msg;
                    }
                },
                convertBack: function (value) {
                    return value;
                },
                beforeEmit: function(msg, value) {
                    return { msg: msg };
                },
                initController: initController
            });

            // 监听节点输入
            node.on('input', function(msg, send, done) {
                // 不自动转发，由前端控制输出（合法走法输出状态，非法走法输出报警）
                if (done) done();
            });

            node.on("close", done);
        } catch (e) {
            console.log(e);
            RED.log.error("[chinese-chess] init error: " + e.message);
        }
    }
    RED.nodes.registerType("chinese-chess", ChineseChessNode);
};
